// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	user "demo/internal/handler/user"
	"demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 演示模块：根据名称返回问候语
				Method:  http.MethodGet,
				Path:    "/get_user",
				Handler: user.DemoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update_user",
				Handler: user.UPDemoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/demo/v1"),
	)
}
