Name: "bin blog"
Env: "dev"
Host: 127.0.0.1
Port: 8080

Mysql:
  Username: "sc"
  Password: "sc123456"
  Host: "42.194.226.141"
  Port: "3306"
  DBname: "gorm"
  Timeout: "10s"
  MaxOpenConns: 100    # 最大连接数
  MaxIdleConns: 10     # 空闲连接数
  ConnMaxLifetime: 30m # 连接最大存活时间

