// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: usercenter_rpc.proto

package usercenterrpcclient

import (
	"context"

	"usercenter_rpc/usercenter_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = usercenter_rpc.Request
	Response = usercenter_rpc.Response

	UsercenterRpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultUsercenterRpc struct {
		cli zrpc.Client
	}
)

func NewUsercenterRpc(cli zrpc.Client) UsercenterRpc {
	return &defaultUsercenterRpc{
		cli: cli,
	}
}

func (m *defaultUsercenterRpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := usercenter_rpc.NewUsercenterRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
