// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type Request struct {
	UserID int64 `form:"userID"`
}

type Response struct {
	Message string `json:"message"`
}

type UpRequest struct {
	UserID   int64  `form:"userID"`
	UserName string `form:"userName"`
}

type UpResponse struct {
	Flag bool
}
