// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: demo_rpc.proto

package server

import (
	"context"

	"demo_rpc/demo_rpc"
	"demo_rpc/internal/logic"
	"demo_rpc/internal/svc"
)

type DemoRpcServer struct {
	svcCtx *svc.ServiceContext
	demo_rpc.UnimplementedDemoRpcServer
}

func NewDemoRpcServer(svcCtx *svc.ServiceContext) *DemoRpcServer {
	return &DemoRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *DemoRpcServer) Ping(ctx context.Context, in *demo_rpc.Request) (*demo_rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
