// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	user "go_zero/usercenter/internal/handler/user"
	"go_zero/usercenter/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 新增用户
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: user.UserCreateHandler(serverCtx),
			},
			{
				// 查询用户信息
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: user.UserInfoHandler(serverCtx),
			},
			{
				// 修改用户信息
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: user.UserUpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/back/v1/user"),
	)
}
