Name: "gin blog"
Env: "dev"
Host: 127.0.0.1
Port: 8080


Mysql:
  Username: "sc"
  Password: "sc123456"
  Host: "42.194.226.141"
  Port: "3306"
  DBname: "gozero"
  Timeout: "10s"
  MaxOpenConns: 100    # 最大连接数
  MaxIdleConns: 10     # 空闲连接数
  ConnMaxLifetime: 30m # 连接最大存活时间

Log:
  LogPath: "logs"  # 日志文件路径
  MaxSize: 20             # 单个文件最大大小(MB)
  MaxBackups: 5           # 保留的旧日志文件数
  MaxAge: 7              # 日志保留天数
  Compress: true           # 是否压缩旧日志

Jwt:
  Secret: "jGudRl2qx0zAbckdK1unsq8vxSy1riQ1HkVTn59qois="
  TokenExpire: 24
  Issuer: "gin blog"