// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: usercenter_rpc.proto

package server

import (
	"context"

	"usercenter_rpc/internal/logic"
	"usercenter_rpc/internal/svc"
	"usercenter_rpc/usercenter_rpc"
)

type UsercenterRpcServer struct {
	svcCtx *svc.ServiceContext
	usercenter_rpc.UnimplementedUsercenterRpcServer
}

func NewUsercenterRpcServer(svcCtx *svc.ServiceContext) *UsercenterRpcServer {
	return &UsercenterRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterRpcServer) Ping(ctx context.Context, in *usercenter_rpc.Request) (*usercenter_rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
