// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: usercenter_rpc.proto

package server

import (
	"context"

	"usercenter_rpc/internal/logic"
	"usercenter_rpc/internal/svc"
	"usercenter_rpc/usercenter_rpc"
)

type UsercenterRpcServer struct {
	svcCtx *svc.ServiceContext
	usercenter_rpc.UnimplementedUsercenterRpcServer
}

func NewUsercenterRpcServer(svcCtx *svc.ServiceContext) *UsercenterRpcServer {
	return &UsercenterRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterRpcServer) GetUserInfo(ctx context.Context, in *usercenter_rpc.GetUserInfoReq) (*usercenter_rpc.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
